/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PerfumesRouteImport } from './routes/perfumes'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendasNovaRouteImport } from './routes/vendas.nova'
import { Route as PedidoSucessoRouteImport } from './routes/pedido.sucesso'
import { Route as CatalogoSlugRouteImport } from './routes/catalogo.$slug'
import { Route as CUserIdRouteImport } from './routes/c.$userId'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfumesRoute = PerfumesRouteImport.update({
  id: '/perfumes',
  path: '/perfumes',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasNovaRoute = VendasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => VendasRoute,
} as any)
const PedidoSucessoRoute = PedidoSucessoRouteImport.update({
  id: '/pedido/sucesso',
  path: '/pedido/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoSlugRoute = CatalogoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CatalogoRoute,
} as any)
const CUserIdRoute = CUserIdRouteImport.update({
  id: '/c/$userId',
  path: '/c/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/pedidos': typeof PedidosRoute
  '/perfumes': typeof PerfumesRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRouteWithChildren
  '/c/$userId': typeof CUserIdRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/vendas/nova': typeof VendasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/pedidos': typeof PedidosRoute
  '/perfumes': typeof PerfumesRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRouteWithChildren
  '/c/$userId': typeof CUserIdRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/vendas/nova': typeof VendasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/pedidos': typeof PedidosRoute
  '/perfumes': typeof PerfumesRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRouteWithChildren
  '/c/$userId': typeof CUserIdRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/vendas/nova': typeof VendasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/clientes'
    | '/pedidos'
    | '/perfumes'
    | '/relatorios'
    | '/vendas'
    | '/c/$userId'
    | '/catalogo/$slug'
    | '/pedido/sucesso'
    | '/vendas/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/clientes'
    | '/pedidos'
    | '/perfumes'
    | '/relatorios'
    | '/vendas'
    | '/c/$userId'
    | '/catalogo/$slug'
    | '/pedido/sucesso'
    | '/vendas/nova'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/clientes'
    | '/pedidos'
    | '/perfumes'
    | '/relatorios'
    | '/vendas'
    | '/c/$userId'
    | '/catalogo/$slug'
    | '/pedido/sucesso'
    | '/vendas/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRouteWithChildren
  ClientesRoute: typeof ClientesRoute
  PedidosRoute: typeof PedidosRoute
  PerfumesRoute: typeof PerfumesRoute
  RelatoriosRoute: typeof RelatoriosRoute
  VendasRoute: typeof VendasRouteWithChildren
  CUserIdRoute: typeof CUserIdRoute
  PedidoSucessoRoute: typeof PedidoSucessoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfumes': {
      id: '/perfumes'
      path: '/perfumes'
      fullPath: '/perfumes'
      preLoaderRoute: typeof PerfumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/nova': {
      id: '/vendas/nova'
      path: '/nova'
      fullPath: '/vendas/nova'
      preLoaderRoute: typeof VendasNovaRouteImport
      parentRoute: typeof VendasRoute
    }
    '/pedido/sucesso': {
      id: '/pedido/sucesso'
      path: '/pedido/sucesso'
      fullPath: '/pedido/sucesso'
      preLoaderRoute: typeof PedidoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$slug': {
      id: '/catalogo/$slug'
      path: '/$slug'
      fullPath: '/catalogo/$slug'
      preLoaderRoute: typeof CatalogoSlugRouteImport
      parentRoute: typeof CatalogoRoute
    }
    '/c/$userId': {
      id: '/c/$userId'
      path: '/c/$userId'
      fullPath: '/c/$userId'
      preLoaderRoute: typeof CUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CatalogoRouteChildren {
  CatalogoSlugRoute: typeof CatalogoSlugRoute
}

const CatalogoRouteChildren: CatalogoRouteChildren = {
  CatalogoSlugRoute: CatalogoSlugRoute,
}

const CatalogoRouteWithChildren = CatalogoRoute._addFileChildren(
  CatalogoRouteChildren,
)

interface VendasRouteChildren {
  VendasNovaRoute: typeof VendasNovaRoute
}

const VendasRouteChildren: VendasRouteChildren = {
  VendasNovaRoute: VendasNovaRoute,
}

const VendasRouteWithChildren =
  VendasRoute._addFileChildren(VendasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRouteWithChildren,
  ClientesRoute: ClientesRoute,
  PedidosRoute: PedidosRoute,
  PerfumesRoute: PerfumesRoute,
  RelatoriosRoute: RelatoriosRoute,
  VendasRoute: VendasRouteWithChildren,
  CUserIdRoute: CUserIdRoute,
  PedidoSucessoRoute: PedidoSucessoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
