/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as PerfumesRouteImport } from './routes/perfumes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendasNovaRouteImport } from './routes/vendas.nova'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfumesRoute = PerfumesRouteImport.update({
  id: '/perfumes',
  path: '/perfumes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasNovaRoute = VendasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => VendasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/perfumes': typeof PerfumesRoute
  '/vendas': typeof VendasRouteWithChildren
  '/vendas/nova': typeof VendasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/perfumes': typeof PerfumesRoute
  '/vendas': typeof VendasRouteWithChildren
  '/vendas/nova': typeof VendasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/perfumes': typeof PerfumesRoute
  '/vendas': typeof VendasRouteWithChildren
  '/vendas/nova': typeof VendasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/perfumes' | '/vendas' | '/vendas/nova'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/perfumes' | '/vendas' | '/vendas/nova'
  id: '__root__' | '/' | '/perfumes' | '/vendas' | '/vendas/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PerfumesRoute: typeof PerfumesRoute
  VendasRoute: typeof VendasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfumes': {
      id: '/perfumes'
      path: '/perfumes'
      fullPath: '/perfumes'
      preLoaderRoute: typeof PerfumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/nova': {
      id: '/vendas/nova'
      path: '/nova'
      fullPath: '/vendas/nova'
      preLoaderRoute: typeof VendasNovaRouteImport
      parentRoute: typeof VendasRoute
    }
  }
}

interface VendasRouteChildren {
  VendasNovaRoute: typeof VendasNovaRoute
}

const VendasRouteChildren: VendasRouteChildren = {
  VendasNovaRoute: VendasNovaRoute,
}

const VendasRouteWithChildren =
  VendasRoute._addFileChildren(VendasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PerfumesRoute: PerfumesRoute,
  VendasRoute: VendasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
